# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just another blog
email: mail -at- andre-bauer.org
description: Blogs and notes...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.andre-bauer.org" # the base hostname & protocol for your site
twitter_username: mono_tek
github_username:  monotek

# Build settings
markdown: kramdown
