baseURL = "https://monotek.github.io"
languageCode = "en-us"
title = "Just another IT(?) blog"
theme = "beautifulhugo"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Just another IT(?) blog"
  facebook = ""
  twitter = "https://twitter.com/monotek"
  instagram = ""
  youtube = ""
  github = "https://github.com/monotek"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/andr%C3%A9-bauer-3a467027"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = ""
  recent_posts_number = 5
  author = "monotek"
  authorlocation = "Dresden, Germany"
  authorwebsite = "http://monotek.github.io"
